
# html lang
language: en

# main menu navigation
menu:
  Home:
    url: /
    icon: fh fh-ravelry
  Category:
    url: /categories
    icon: fh fh-cubes
  Tag:
    url: /tags
    icon: fh fh-tags
  Archives:
    url: /archives
    icon: fh fh-archive
  About:
    url: /about
    icon: fh fh-about

# RSS
rss: /atom.xml

# headImg url and gravatar
headImg:
  url: /img/logo.jpg
  gravatar:
    email:
    option:

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/hannah.css

# scripts loaded in the end of the body
scripts:
- /js/hannah.js

highlight_theme: normal